#!/usr/bin/env python
import sys
width = 10
height = 22
emp_row = width* ". "
command = sys.stdin.readline()
if command.strip() == 'p':
    for y in range(0, height):
        sys.stdout.write(emp_row)
        sys.stdout.write("\n")
